const translations = {
  "en": {
    "nav_about": "About",
    "nav_status": "Live",
    "nav_tokenomics": "Tokenomics",
    "nav_whitepaper": "Whitepaper",
    "nav_roadmap": "Roadmap",
    "nav_faq": "FAQ",
    "buy_btcwh": "Buy BTCWH",
    "hero_eyebrow": "BTCWH • SOLANA • LIVE TOKEN",
    "hero_title_1": "The Time Has Come.",
    "hero_title_2": "Now BTCWH.",
    "hero_lead": "BTC White is a next-generation digital asset live on Solana, built around a white and silver identity, fixed supply, transparent tokenomics, and a long-term payment ecosystem vision.",
    "open_raydium": "Open Raydium",
    "download_whitepaper": "Download Whitepaper",
    "total_supply": "Total Supply",
    "blockchain": "Blockchain",
    "symbol": "Token Symbol",
    "status_eyebrow": "Current Status",
    "status_title": "BTCWH is live on Solana.",
    "status_text": "The BTCWH token has been created on Solana and is available through the BTCWH/SOL market. Always verify the official token address before trading.",
    "contract_title": "Token Address",
    "view_token": "View token",
    "trade_pair": "Trade BTCWH/SOL",
    "view_chart": "View chart",
    "about_eyebrow": "About BTCWH",
    "about_title": "BTC White is built for a new digital generation.",
    "about_text": "BTC White combines a premium white/silver brand identity with a clear economic model and a long-term mission: to develop BTCWH into a usable digital payment instrument within its ecosystem and with future partners where permitted by law.",
    "advantages_eyebrow": "Advantages",
    "advantages_title": "Why BTCWH?",
    "adv1_title": "Fixed Supply",
    "adv1_text": "Maximum supply is limited to 21,000,000 BTCWH.",
    "adv2_title": "Transparent Model",
    "adv2_text": "Clear allocation for liquidity, strategic reserve, marketing, team, ecosystem development, and community participation.",
    "adv3_title": "Community Driven",
    "adv3_text": "The project is designed to grow through community, partners, market visibility, and long-term utility.",
    "adv4_title": "Security First",
    "adv4_text": "Official information is published through btcwh.io. Users should verify links and never share private keys or seed phrases.",
    "tokenomics_eyebrow": "Tokenomics",
    "tokenomics_title": "21 million BTCWH. Clear allocation.",
    "category": "Category",
    "share": "Share",
    "tokens": "Tokens",
    "liq": "Liquidity",
    "team": "Team & Development",
    "reserve": "Strategic Reserve",
    "marketing": "Marketing & Growth",
    "founders_presale": "Community / Early Distribution",
    "whitepaper_eyebrow": "Whitepaper",
    "whitepaper_title": "Official BTC White Whitepaper.",
    "whitepaper_text": "Download the official BTC White Whitepaper in your preferred language. The document describes mission, tokenomics, roadmap, security principles, BTCWH Pay vision, and long-term ecosystem strategy.",
    "roadmap_eyebrow": "Roadmap",
    "roadmap_title": "From brand foundation to BTCWH Pay.",
    "phase1": "Phase 1",
    "phase1_text": "Brand, logo, domain, website, Whitepaper.",
    "phase2": "Phase 2",
    "phase2_text": "Token creation, initial liquidity, Solana ecosystem presence.",
    "phase3": "Phase 3",
    "phase3_text": "DEX trading, market visibility, OTC distribution channels.",
    "phase4": "Phase 4",
    "phase4_text": "Partnerships, BTCWH Pay research, global ecosystem expansion.",
    "faq_title": "Common questions.",
    "faq1_q": "What is BTCWH?",
    "faq1_a": "BTCWH is the ticker for BTC White, a digital asset project with a long-term payment ecosystem vision.",
    "faq2_q": "What is the official website?",
    "faq2_a": "The official website is btcwh.io.",
    "faq3_q": "Where can I verify BTCWH?",
    "faq3_a": "Use the official token address on Solscan and always verify links from btcwh.io.",
    "faq4_q": "Which blockchain does BTCWH use?",
    "faq4_a": "BTCWH is issued on the Solana network.",
    "footer": "© 2026 BTC White. The Time Has Come. Now BTCWH."
  },
  "ru": {
    "nav_about": "О проекте",
    "nav_status": "Запущен",
    "nav_tokenomics": "Токеномика",
    "nav_whitepaper": "Whitepaper",
    "nav_roadmap": "План",
    "nav_faq": "FAQ",
    "buy_btcwh": "Купить BTCWH",
    "hero_eyebrow": "BTCWH • SOLANA • ТОКЕН УЖЕ ЗАПУЩЕН",
    "hero_title_1": "Время пришло.",
    "hero_title_2": "Теперь BTCWH.",
    "hero_lead": "BTC White — цифровой актив нового поколения, уже запущенный в сети Solana. Проект построен вокруг бело-серебристого бренда, фиксированной эмиссии, прозрачной токеномики и долгосрочной идеи платежной экосистемы.",
    "open_raydium": "Открыть Raydium",
    "download_whitepaper": "Скачать Whitepaper",
    "total_supply": "Общая эмиссия",
    "blockchain": "Блокчейн",
    "symbol": "Символ токена",
    "status_eyebrow": "Текущий статус",
    "status_title": "BTCWH уже запущен на Solana.",
    "status_text": "Токен BTCWH создан в сети Solana и доступен через рынок BTCWH/SOL. Перед торговлей всегда проверяйте официальный адрес токена.",
    "contract_title": "Адрес токена",
    "view_token": "Смотреть токен",
    "trade_pair": "Торговать BTCWH/SOL",
    "view_chart": "Смотреть график",
    "about_eyebrow": "О BTCWH",
    "about_title": "BTC White создан для нового цифрового поколения.",
    "about_text": "BTC White объединяет премиальный бело-серебристый бренд, понятную экономическую модель и долгосрочную миссию: развивать BTCWH как цифровой платежный инструмент внутри экосистемы и у будущих партнеров там, где это разрешено законом.",
    "advantages_eyebrow": "Преимущества",
    "advantages_title": "Почему BTCWH?",
    "adv1_title": "Фиксированная эмиссия",
    "adv1_text": "Максимальная эмиссия ограничена 21 000 000 BTCWH.",
    "adv2_title": "Прозрачная модель",
    "adv2_text": "Понятное распределение для ликвидности, стратегического резерва, маркетинга, команды, развития экосистемы и участия сообщества.",
    "adv3_title": "Рост через сообщество",
    "adv3_text": "Проект рассчитан на развитие через сообщество, партнеров, рыночную узнаваемость и долгосрочную практическую пользу.",
    "adv4_title": "Безопасность прежде всего",
    "adv4_text": "Официальная информация публикуется через btcwh.io. Пользователи должны проверять ссылки и никогда не передавать приватные ключи или seed-фразы.",
    "tokenomics_eyebrow": "Токеномика",
    "tokenomics_title": "21 миллион BTCWH. Четкое распределение.",
    "category": "Категория",
    "share": "Доля",
    "tokens": "Токены",
    "liq": "Ликвидность",
    "team": "Команда и разработка",
    "reserve": "Стратегический резерв",
    "marketing": "Маркетинг и рост",
    "founders_presale": "Сообщество / раннее распределение",
    "whitepaper_eyebrow": "Whitepaper",
    "whitepaper_title": "Официальный Whitepaper BTC White.",
    "whitepaper_text": "Скачайте официальный Whitepaper BTC White на нужном языке. Документ описывает миссию, токеномику, дорожную карту, принципы безопасности, видение BTCWH Pay и долгосрочную стратегию экосистемы.",
    "roadmap_eyebrow": "Дорожная карта",
    "roadmap_title": "От основы бренда до BTCWH Pay.",
    "phase1": "Этап 1",
    "phase1_text": "Бренд, логотип, домен, сайт, Whitepaper.",
    "phase2": "Этап 2",
    "phase2_text": "Создание токена, начальная ликвидность, присутствие в экосистеме Solana.",
    "phase3": "Этап 3",
    "phase3_text": "DEX-торговля, рыночная узнаваемость, OTC-каналы распределения.",
    "phase4": "Этап 4",
    "phase4_text": "Партнерства, исследование BTCWH Pay, глобальное расширение экосистемы.",
    "faq_title": "Частые вопросы.",
    "faq1_q": "Что такое BTCWH?",
    "faq1_a": "BTCWH — тикер BTC White, цифрового актива с долгосрочной идеей платежной экосистемы.",
    "faq2_q": "Какой официальный сайт?",
    "faq2_a": "Официальный сайт — btcwh.io.",
    "faq3_q": "Где проверить BTCWH?",
    "faq3_a": "Используйте официальный адрес токена в Solscan и всегда проверяйте ссылки через btcwh.io.",
    "faq4_q": "В какой сети работает BTCWH?",
    "faq4_a": "BTCWH выпущен в сети Solana.",
    "footer": "© 2026 BTC White. Время пришло. Теперь BTCWH."
  },
  "es": {
    "nav_about": "Acerca de",
    "nav_status": "Activo",
    "nav_tokenomics": "Tokenomics",
    "nav_whitepaper": "Whitepaper",
    "nav_roadmap": "Roadmap",
    "nav_faq": "FAQ",
    "buy_btcwh": "Comprar BTCWH",
    "hero_eyebrow": "BTCWH • SOLANA • TOKEN ACTIVO",
    "hero_title_1": "Ha llegado el momento.",
    "hero_title_2": "Ahora BTCWH.",
    "hero_lead": "BTC White is a next-generation digital asset live on Solana, built around a white and silver identity, fixed supply, transparent tokenomics, and a long-term payment ecosystem vision.",
    "open_raydium": "Abrir Raydium",
    "download_whitepaper": "Descargar Whitepaper",
    "total_supply": "Suministro total",
    "blockchain": "Blockchain",
    "symbol": "Símbolo",
    "status_eyebrow": "Current Status",
    "status_title": "BTCWH está activo en Solana.",
    "status_text": "The BTCWH token has been created on Solana and is available through the BTCWH/SOL market. Always verify the official token address before trading.",
    "contract_title": "Dirección del token",
    "view_token": "Ver token",
    "trade_pair": "Operar BTCWH/SOL",
    "view_chart": "Ver gráfico",
    "about_eyebrow": "About BTCWH",
    "about_title": "BTC White is built for a new digital generation.",
    "about_text": "BTC White combines a premium white/silver brand identity with a clear economic model and a long-term mission: to develop BTCWH into a usable digital payment instrument within its ecosystem and with future partners where permitted by law.",
    "advantages_eyebrow": "Advantages",
    "advantages_title": "Why BTCWH?",
    "adv1_title": "Fixed Supply",
    "adv1_text": "Maximum supply is limited to 21,000,000 BTCWH.",
    "adv2_title": "Transparent Model",
    "adv2_text": "Clear allocation for liquidity, strategic reserve, marketing, team, ecosystem development, and community participation.",
    "adv3_title": "Community Driven",
    "adv3_text": "The project is designed to grow through community, partners, market visibility, and long-term utility.",
    "adv4_title": "Security First",
    "adv4_text": "Official information is published through btcwh.io. Users should verify links and never share private keys or seed phrases.",
    "tokenomics_eyebrow": "Tokenomics",
    "tokenomics_title": "21 million BTCWH. Clear allocation.",
    "category": "Categoría",
    "share": "Porcentaje",
    "tokens": "Tokens",
    "liq": "Liquidez",
    "team": "Equipo y desarrollo",
    "reserve": "Reserva estratégica",
    "marketing": "Marketing y crecimiento",
    "founders_presale": "Community / Early Distribution",
    "whitepaper_eyebrow": "Whitepaper",
    "whitepaper_title": "Whitepaper oficial de BTC White.",
    "whitepaper_text": "Download the official BTC White Whitepaper in your preferred language. The document describes mission, tokenomics, roadmap, security principles, BTCWH Pay vision, and long-term ecosystem strategy.",
    "roadmap_eyebrow": "Roadmap",
    "roadmap_title": "From brand foundation to BTCWH Pay.",
    "phase1": "Phase 1",
    "phase1_text": "Brand, logo, domain, website, Whitepaper.",
    "phase2": "Phase 2",
    "phase2_text": "Token creation, initial liquidity, Solana ecosystem presence.",
    "phase3": "Phase 3",
    "phase3_text": "DEX trading, market visibility, OTC distribution channels.",
    "phase4": "Phase 4",
    "phase4_text": "Partnerships, BTCWH Pay research, global ecosystem expansion.",
    "faq_title": "Preguntas frecuentes.",
    "faq1_q": "What is BTCWH?",
    "faq1_a": "BTCWH is the ticker for BTC White, a digital asset project with a long-term payment ecosystem vision.",
    "faq2_q": "What is the official website?",
    "faq2_a": "The official website is btcwh.io.",
    "faq3_q": "Where can I verify BTCWH?",
    "faq3_a": "Use the official token address on Solscan and always verify links from btcwh.io.",
    "faq4_q": "Which blockchain does BTCWH use?",
    "faq4_a": "BTCWH is issued on the Solana network.",
    "footer": "© 2026 BTC White. Ha llegado el momento. Ahora BTCWH."
  },
  "zh": {
    "nav_about": "关于",
    "nav_status": "已上线",
    "nav_tokenomics": "代币经济",
    "nav_whitepaper": "白皮书",
    "nav_roadmap": "路线图",
    "nav_faq": "FAQ",
    "buy_btcwh": "购买 BTCWH",
    "hero_eyebrow": "BTCWH • SOLANA • 已上线代币",
    "hero_title_1": "时机已到。",
    "hero_title_2": "现在是 BTCWH。",
    "hero_lead": "BTC White is a next-generation digital asset live on Solana, built around a white and silver identity, fixed supply, transparent tokenomics, and a long-term payment ecosystem vision.",
    "open_raydium": "打开 Raydium",
    "download_whitepaper": "下载白皮书",
    "total_supply": "总供应量",
    "blockchain": "区块链",
    "symbol": "代币符号",
    "status_eyebrow": "Current Status",
    "status_title": "BTCWH 已在 Solana 上线。",
    "status_text": "The BTCWH token has been created on Solana and is available through the BTCWH/SOL market. Always verify the official token address before trading.",
    "contract_title": "代币地址",
    "view_token": "查看代币",
    "trade_pair": "交易 BTCWH/SOL",
    "view_chart": "查看图表",
    "about_eyebrow": "About BTCWH",
    "about_title": "BTC White is built for a new digital generation.",
    "about_text": "BTC White combines a premium white/silver brand identity with a clear economic model and a long-term mission: to develop BTCWH into a usable digital payment instrument within its ecosystem and with future partners where permitted by law.",
    "advantages_eyebrow": "Advantages",
    "advantages_title": "Why BTCWH?",
    "adv1_title": "Fixed Supply",
    "adv1_text": "Maximum supply is limited to 21,000,000 BTCWH.",
    "adv2_title": "Transparent Model",
    "adv2_text": "Clear allocation for liquidity, strategic reserve, marketing, team, ecosystem development, and community participation.",
    "adv3_title": "Community Driven",
    "adv3_text": "The project is designed to grow through community, partners, market visibility, and long-term utility.",
    "adv4_title": "Security First",
    "adv4_text": "Official information is published through btcwh.io. Users should verify links and never share private keys or seed phrases.",
    "tokenomics_eyebrow": "Tokenomics",
    "tokenomics_title": "21 million BTCWH. Clear allocation.",
    "category": "类别",
    "share": "比例",
    "tokens": "代币",
    "liq": "流动性",
    "team": "团队与开发",
    "reserve": "战略储备",
    "marketing": "营销与增长",
    "founders_presale": "Community / Early Distribution",
    "whitepaper_eyebrow": "Whitepaper",
    "whitepaper_title": "BTC White 官方白皮书。",
    "whitepaper_text": "Download the official BTC White Whitepaper in your preferred language. The document describes mission, tokenomics, roadmap, security principles, BTCWH Pay vision, and long-term ecosystem strategy.",
    "roadmap_eyebrow": "Roadmap",
    "roadmap_title": "From brand foundation to BTCWH Pay.",
    "phase1": "Phase 1",
    "phase1_text": "Brand, logo, domain, website, Whitepaper.",
    "phase2": "Phase 2",
    "phase2_text": "Token creation, initial liquidity, Solana ecosystem presence.",
    "phase3": "Phase 3",
    "phase3_text": "DEX trading, market visibility, OTC distribution channels.",
    "phase4": "Phase 4",
    "phase4_text": "Partnerships, BTCWH Pay research, global ecosystem expansion.",
    "faq_title": "常见问题",
    "faq1_q": "What is BTCWH?",
    "faq1_a": "BTCWH is the ticker for BTC White, a digital asset project with a long-term payment ecosystem vision.",
    "faq2_q": "What is the official website?",
    "faq2_a": "The official website is btcwh.io.",
    "faq3_q": "Where can I verify BTCWH?",
    "faq3_a": "Use the official token address on Solscan and always verify links from btcwh.io.",
    "faq4_q": "Which blockchain does BTCWH use?",
    "faq4_a": "BTCWH is issued on the Solana network.",
    "footer": "© 2026 BTC White. 时机已到。现在是 BTCWH。"
  },
  "ko": {
    "nav_about": "소개",
    "nav_status": "라이브",
    "nav_tokenomics": "토크노믹스",
    "nav_whitepaper": "백서",
    "nav_roadmap": "로드맵",
    "nav_faq": "FAQ",
    "buy_btcwh": "BTCWH 구매",
    "hero_eyebrow": "BTCWH • SOLANA • 라이브 토큰",
    "hero_title_1": "시간이 왔습니다.",
    "hero_title_2": "이제 BTCWH.",
    "hero_lead": "BTC White is a next-generation digital asset live on Solana, built around a white and silver identity, fixed supply, transparent tokenomics, and a long-term payment ecosystem vision.",
    "open_raydium": "Raydium 열기",
    "download_whitepaper": "백서 다운로드",
    "total_supply": "총 공급량",
    "blockchain": "블록체인",
    "symbol": "토큰 심볼",
    "status_eyebrow": "Current Status",
    "status_title": "BTCWH는 Solana에서 라이브입니다.",
    "status_text": "The BTCWH token has been created on Solana and is available through the BTCWH/SOL market. Always verify the official token address before trading.",
    "contract_title": "토큰 주소",
    "view_token": "토큰 보기",
    "trade_pair": "BTCWH/SOL 거래",
    "view_chart": "차트 보기",
    "about_eyebrow": "About BTCWH",
    "about_title": "BTC White is built for a new digital generation.",
    "about_text": "BTC White combines a premium white/silver brand identity with a clear economic model and a long-term mission: to develop BTCWH into a usable digital payment instrument within its ecosystem and with future partners where permitted by law.",
    "advantages_eyebrow": "Advantages",
    "advantages_title": "Why BTCWH?",
    "adv1_title": "Fixed Supply",
    "adv1_text": "Maximum supply is limited to 21,000,000 BTCWH.",
    "adv2_title": "Transparent Model",
    "adv2_text": "Clear allocation for liquidity, strategic reserve, marketing, team, ecosystem development, and community participation.",
    "adv3_title": "Community Driven",
    "adv3_text": "The project is designed to grow through community, partners, market visibility, and long-term utility.",
    "adv4_title": "Security First",
    "adv4_text": "Official information is published through btcwh.io. Users should verify links and never share private keys or seed phrases.",
    "tokenomics_eyebrow": "Tokenomics",
    "tokenomics_title": "21 million BTCWH. Clear allocation.",
    "category": "카테고리",
    "share": "비율",
    "tokens": "토큰",
    "liq": "유동성",
    "team": "팀 및 개발",
    "reserve": "전략 준비금",
    "marketing": "마케팅 및 성장",
    "founders_presale": "Community / Early Distribution",
    "whitepaper_eyebrow": "Whitepaper",
    "whitepaper_title": "공식 BTC White 백서.",
    "whitepaper_text": "Download the official BTC White Whitepaper in your preferred language. The document describes mission, tokenomics, roadmap, security principles, BTCWH Pay vision, and long-term ecosystem strategy.",
    "roadmap_eyebrow": "Roadmap",
    "roadmap_title": "From brand foundation to BTCWH Pay.",
    "phase1": "Phase 1",
    "phase1_text": "Brand, logo, domain, website, Whitepaper.",
    "phase2": "Phase 2",
    "phase2_text": "Token creation, initial liquidity, Solana ecosystem presence.",
    "phase3": "Phase 3",
    "phase3_text": "DEX trading, market visibility, OTC distribution channels.",
    "phase4": "Phase 4",
    "phase4_text": "Partnerships, BTCWH Pay research, global ecosystem expansion.",
    "faq_title": "자주 묻는 질문",
    "faq1_q": "What is BTCWH?",
    "faq1_a": "BTCWH is the ticker for BTC White, a digital asset project with a long-term payment ecosystem vision.",
    "faq2_q": "What is the official website?",
    "faq2_a": "The official website is btcwh.io.",
    "faq3_q": "Where can I verify BTCWH?",
    "faq3_a": "Use the official token address on Solscan and always verify links from btcwh.io.",
    "faq4_q": "Which blockchain does BTCWH use?",
    "faq4_a": "BTCWH is issued on the Solana network.",
    "footer": "© 2026 BTC White. 시간이 왔습니다. 이제 BTCWH."
  },
  "hi": {
    "nav_about": "परिचय",
    "nav_status": "लाइव",
    "nav_tokenomics": "टोकनोमिक्स",
    "nav_whitepaper": "Whitepaper",
    "nav_roadmap": "रोडमैप",
    "nav_faq": "FAQ",
    "buy_btcwh": "BTCWH खरीदें",
    "hero_eyebrow": "BTCWH • SOLANA • लाइव टोकन",
    "hero_title_1": "समय आ गया है।",
    "hero_title_2": "अब BTCWH।",
    "hero_lead": "BTC White is a next-generation digital asset live on Solana, built around a white and silver identity, fixed supply, transparent tokenomics, and a long-term payment ecosystem vision.",
    "open_raydium": "Raydium खोलें",
    "download_whitepaper": "Whitepaper डाउनलोड करें",
    "total_supply": "कुल सप्लाई",
    "blockchain": "ब्लॉकचेन",
    "symbol": "टोकन सिंबल",
    "status_eyebrow": "Current Status",
    "status_title": "BTCWH Solana पर लाइव है।",
    "status_text": "The BTCWH token has been created on Solana and is available through the BTCWH/SOL market. Always verify the official token address before trading.",
    "contract_title": "टोकन पता",
    "view_token": "टोकन देखें",
    "trade_pair": "BTCWH/SOL ट्रेड करें",
    "view_chart": "चार्ट देखें",
    "about_eyebrow": "About BTCWH",
    "about_title": "BTC White is built for a new digital generation.",
    "about_text": "BTC White combines a premium white/silver brand identity with a clear economic model and a long-term mission: to develop BTCWH into a usable digital payment instrument within its ecosystem and with future partners where permitted by law.",
    "advantages_eyebrow": "Advantages",
    "advantages_title": "Why BTCWH?",
    "adv1_title": "Fixed Supply",
    "adv1_text": "Maximum supply is limited to 21,000,000 BTCWH.",
    "adv2_title": "Transparent Model",
    "adv2_text": "Clear allocation for liquidity, strategic reserve, marketing, team, ecosystem development, and community participation.",
    "adv3_title": "Community Driven",
    "adv3_text": "The project is designed to grow through community, partners, market visibility, and long-term utility.",
    "adv4_title": "Security First",
    "adv4_text": "Official information is published through btcwh.io. Users should verify links and never share private keys or seed phrases.",
    "tokenomics_eyebrow": "Tokenomics",
    "tokenomics_title": "21 million BTCWH. Clear allocation.",
    "category": "श्रेणी",
    "share": "हिस्सा",
    "tokens": "टोकन",
    "liq": "लिक्विडिटी",
    "team": "टीम और विकास",
    "reserve": "रणनीतिक रिजर्व",
    "marketing": "मार्केटिंग और विकास",
    "founders_presale": "Community / Early Distribution",
    "whitepaper_eyebrow": "Whitepaper",
    "whitepaper_title": "आधिकारिक BTC White Whitepaper.",
    "whitepaper_text": "Download the official BTC White Whitepaper in your preferred language. The document describes mission, tokenomics, roadmap, security principles, BTCWH Pay vision, and long-term ecosystem strategy.",
    "roadmap_eyebrow": "Roadmap",
    "roadmap_title": "From brand foundation to BTCWH Pay.",
    "phase1": "Phase 1",
    "phase1_text": "Brand, logo, domain, website, Whitepaper.",
    "phase2": "Phase 2",
    "phase2_text": "Token creation, initial liquidity, Solana ecosystem presence.",
    "phase3": "Phase 3",
    "phase3_text": "DEX trading, market visibility, OTC distribution channels.",
    "phase4": "Phase 4",
    "phase4_text": "Partnerships, BTCWH Pay research, global ecosystem expansion.",
    "faq_title": "सामान्य प्रश्न",
    "faq1_q": "What is BTCWH?",
    "faq1_a": "BTCWH is the ticker for BTC White, a digital asset project with a long-term payment ecosystem vision.",
    "faq2_q": "What is the official website?",
    "faq2_a": "The official website is btcwh.io.",
    "faq3_q": "Where can I verify BTCWH?",
    "faq3_a": "Use the official token address on Solscan and always verify links from btcwh.io.",
    "faq4_q": "Which blockchain does BTCWH use?",
    "faq4_a": "BTCWH is issued on the Solana network.",
    "footer": "© 2026 BTC White. समय आ गया है। अब BTCWH."
  }
};


function setLang(lang) {
  const t = Object.assign({}, translations.en, translations[lang] || {});
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.dataset.i18n;
    if (Object.prototype.hasOwnProperty.call(t, key)) el.textContent = t[key];
  });
  localStorage.setItem("btcwh_lang", lang);
  document.documentElement.lang = lang;
}

document.addEventListener("DOMContentLoaded", () => {
  const languageSelect = document.getElementById("languageSelect");
  const savedLang = localStorage.getItem("btcwh_lang") || "en";
  if (languageSelect) {
    languageSelect.value = translations[savedLang] ? savedLang : "en";
    setLang(languageSelect.value);
    languageSelect.addEventListener("change", e => setLang(e.target.value));
  }

  const themeToggle = document.getElementById("themeToggle");
  function applyTheme(mode) {
    document.body.classList.toggle("dark", mode === "dark");
    if (themeToggle) themeToggle.textContent = mode === "dark" ? "☀️" : "🌙";
    localStorage.setItem("btcwh_theme", mode);
  }
  applyTheme(localStorage.getItem("btcwh_theme") || "light");
  if (themeToggle) {
    themeToggle.addEventListener("click", () => {
      const next = document.body.classList.contains("dark") ? "light" : "dark";
      applyTheme(next);
    });
  }

  const items = document.querySelectorAll(".reveal");
  if ("IntersectionObserver" in window) {
    const obs = new IntersectionObserver(entries => entries.forEach(e => {
      if (e.isIntersecting) e.target.classList.add("visible");
    }), { threshold: 0.1 });
    items.forEach(i => obs.observe(i));
  } else {
    items.forEach(i => i.classList.add("visible"));
  }
});
