const translations = {
  "en": {
    "nav_about": "About",
    "nav_tokenomics": "Tokenomics",
    "nav_presale": "Presale",
    "nav_roadmap": "Roadmap",
    "nav_faq": "FAQ",
    "connect_wallet": "Connect Wallet",
    "hero_eyebrow": "BTCWH • SOLANA • GLOBAL PAYMENT VISION",
    "hero_title_1": "The Time for BTCWH Has Come.",
    "hero_title_2": "",
    "hero_lead": "BTC White is a next-generation digital asset with a fixed supply of 21,000,000 coins, transparent tokenomics, and a focus on real-world payments. We are building an ecosystem where cryptocurrency becomes a practical tool for everyday use.",
    "buy_btcwh": "Buy BTCWH",
    "download_whitepaper": "Download Whitepaper",
    "total_supply": "Total Supply",
    "presale_price": "Presale Price",
    "minimum_purchase": "Minimum Purchase",
    "about_eyebrow": "About BTCWH",
    "about_title": "BTC White is built for a new digital generation.",
    "about_text": "The project combines a premium white/silver brand identity with a clear economic model and a long-term mission: to develop BTCWH into a usable digital payment instrument within its ecosystem and with future partners where permitted by law.",
    "advantages_eyebrow": "Advantages",
    "advantages_title": "Why BTCWH?",
    "adv1_title": "Fixed Supply",
    "adv1_text": "Maximum emission is limited to 21,000,000 BTCWH.",
    "adv2_title": "Transparent Model",
    "adv2_text": "Clear allocation for liquidity, reserve, marketing, team, and presale.",
    "adv3_title": "Community Driven",
    "adv3_text": "The project is designed to grow through community, partners, and long-term utility.",
    "adv4_title": "Secure Foundation",
    "adv4_text": "btcwh.io is protected by Cloudflare and ready for global publication.",
    "tokenomics_eyebrow": "Tokenomics",
    "tokenomics_title": "21 million BTCWH. Clear allocation.",
    "category": "Category",
    "share": "Share",
    "tokens": "Tokens",
    "liq": "Liquidity",
    "team": "Team",
    "reserve": "Reserve",
    "marketing": "Marketing",
    "founders_presale": "Founders Presale",
    "presale_eyebrow": "Founders Presale",
    "presale_title": "Early access phase.",
    "presale_text": "The presale continues until the allocated amount of 1,050,000 BTCWH is fully sold.",
    "price": "Price",
    "minimum": "Minimum",
    "maximum": "Maximum",
    "allocation": "Allocation",
    "presale_soon": "Presale Coming Soon",
    "presale_note": "Official contract address and payment instructions will be published only on btcwh.io and official BTCWH channels.",
    "roadmap_eyebrow": "Roadmap",
    "roadmap_title": "From brand foundation to BTCWH Pay.",
    "phase1": "Phase 1",
    "phase1_text": "Brand, logo, domain, Cloudflare, website.",
    "phase2": "Phase 2",
    "phase2_text": "Whitepaper, community, presale infrastructure.",
    "phase3": "Phase 3",
    "phase3_text": "Token launch, liquidity, DEX listing, LP lock.",
    "phase4": "Phase 4",
    "phase4_text": "Partnerships, BTCWH Pay, global ecosystem.",
    "whitepaper_eyebrow": "Whitepaper",
    "whitepaper_title": "Official documentation will be published here.",
    "whitepaper_text": "The BTCWH Whitepaper will include project mission, tokenomics, roadmap, reserve rules, presale rules and ecosystem vision.",
    "whitepaper_soon": "Download Whitepaper Soon",
    "faq_title": "Common questions.",
    "faq1_q": "What is BTCWH?",
    "faq1_a": "BTCWH is the ticker for BTC White, a digital asset project with a long-term payment ecosystem vision.",
    "faq2_q": "What is the official website?",
    "faq2_a": "The official website is btcwh.io.",
    "faq3_q": "What is the presale minimum?",
    "faq3_a": "The minimum Founders Presale purchase is 10 USDT.",
    "faq4_q": "Which blockchain will BTCWH use?",
    "faq4_a": "BTCWH is planned for the Solana network.",
    "footer": "© 2026 BTC White. The Time for BTCWH Has Come.",
    "wallet_soon_title": "Wallet connection is coming soon",
    "wallet_soon_text": "The official BTCWH presale wallet connection will be enabled only after the token contract and presale smart contract are published."
  },
  "ru": {
    "nav_about": "О проекте",
    "nav_tokenomics": "Токеномика",
    "nav_presale": "Presale",
    "nav_roadmap": "План",
    "nav_faq": "FAQ",
    "connect_wallet": "Подключить кошелек",
    "hero_eyebrow": "BTCWH • SOLANA • ГЛОБАЛЬНАЯ ПЛАТЕЖНАЯ ИДЕЯ",
    "hero_title_1": "Время BTCWH пришло.",
    "hero_title_2": "",
    "hero_lead": "BTC White — это цифровой актив нового поколения с фиксированной эмиссией 21 000 000 монет, прозрачной токеномикой и ориентацией на реальные платежи. Мы создаем экосистему, где криптовалюта становится удобным инструментом для ежедневного использования.",
    "buy_btcwh": "Купить BTCWH",
    "download_whitepaper": "Скачать Whitepaper",
    "total_supply": "Общая эмиссия",
    "presale_price": "Цена Presale",
    "minimum_purchase": "Минимальная покупка",
    "about_eyebrow": "О BTCWH",
    "about_title": "BTC White создан для нового цифрового поколения.",
    "about_text": "Проект объединяет премиальный бело-серебристый бренд, понятную экономическую модель и долгосрочную миссию: развивать BTCWH как цифровой платежный инструмент внутри экосистемы и у будущих партнеров.",
    "advantages_eyebrow": "Преимущества",
    "advantages_title": "Почему BTCWH?",
    "adv1_title": "Ограниченная эмиссия",
    "adv1_text": "Максимальная эмиссия ограничена 21 000 000 BTCWH.",
    "adv2_title": "Прозрачная модель",
    "adv2_text": "Понятное распределение для ликвидности, резерва, маркетинга, команды и пресейла.",
    "adv3_title": "Развитие через сообщество",
    "adv3_text": "Проект рассчитан на рост через сообщество, партнеров и долгосрочную пользу.",
    "adv4_title": "Безопасная основа",
    "adv4_text": "btcwh.io защищен Cloudflare и готов для международной публикации.",
    "tokenomics_eyebrow": "Токеномика",
    "tokenomics_title": "21 миллион BTCWH. Четкое распределение.",
    "category": "Категория",
    "share": "Доля",
    "tokens": "Токены",
    "liq": "Ликвидность",
    "team": "Команда",
    "reserve": "Резерв",
    "marketing": "Маркетинг",
    "founders_presale": "Founders Presale",
    "presale_eyebrow": "Founders Presale",
    "presale_title": "Ранний этап доступа.",
    "presale_text": "Presale продолжается до полной продажи выделенного объема 1 050 000 BTCWH.",
    "price": "Цена",
    "minimum": "Минимум",
    "maximum": "Максимум",
    "allocation": "Выделено",
    "presale_soon": "Presale скоро",
    "presale_note": "Официальный адрес контракта и инструкции по оплате будут опубликованы только на btcwh.io и официальных каналах BTCWH.",
    "roadmap_eyebrow": "Дорожная карта",
    "roadmap_title": "От бренда до BTCWH Pay.",
    "phase1": "Этап 1",
    "phase1_text": "Бренд, логотип, домен, Cloudflare, сайт.",
    "phase2": "Этап 2",
    "phase2_text": "Whitepaper, сообщество, инфраструктура пресейла.",
    "phase3": "Этап 3",
    "phase3_text": "Запуск токена, ликвидность, DEX-листинг, блокировка LP.",
    "phase4": "Этап 4",
    "phase4_text": "Партнерства, BTCWH Pay, глобальная экосистема.",
    "whitepaper_eyebrow": "Whitepaper",
    "whitepaper_title": "Официальная документация будет опубликована здесь.",
    "whitepaper_text": "Whitepaper BTCWH будет включать миссию проекта, токеномику, дорожную карту, правила резерва, правила пресейла и видение экосистемы.",
    "whitepaper_soon": "Whitepaper скоро",
    "faq_title": "Частые вопросы.",
    "faq1_q": "Что такое BTCWH?",
    "faq1_a": "BTCWH — тикер BTC White, цифрового актива с долгосрочной платежной экосистемной идеей.",
    "faq2_q": "Какой официальный сайт?",
    "faq2_a": "Официальный сайт — btcwh.io.",
    "faq3_q": "Какая минимальная покупка на Presale?",
    "faq3_a": "Минимальная покупка Founders Presale — 10 USDT.",
    "faq4_q": "В какой сети будет BTCWH?",
    "faq4_a": "BTCWH планируется в сети Solana.",
    "footer": "© 2026 BTC White. Время BTCWH пришло.",
    "wallet_soon_title": "Подключение кошелька скоро",
    "wallet_soon_text": "Официальное подключение кошелька BTCWH Presale будет включено только после публикации контракта токена и смарт-контракта пресейла."
  },
  "zh": {
    "nav_about": "关于",
    "nav_tokenomics": "代币经济",
    "nav_presale": "预售",
    "nav_roadmap": "路线图",
    "nav_faq": "FAQ",
    "connect_wallet": "连接钱包",
    "hero_eyebrow": "BTCWH • SOLANA • 全球支付愿景",
    "hero_title_1": "BTCWH 时代已经到来。",
    "hero_title_2": "",
    "hero_lead": "BTC White 是新一代数字资产，总发行量固定为 21,000,000 枚，拥有透明的代币经济模型，并专注于现实世界支付。我们正在构建一个生态系统，使加密货币成为日常生活中的实用支付工具。",
    "buy_btcwh": "购买 BTCWH",
    "download_whitepaper": "下载白皮书",
    "total_supply": "总供应量",
    "presale_price": "预售价格",
    "minimum_purchase": "最低购买",
    "about_eyebrow": "关于 BTCWH",
    "about_title": "BTC White 为新数字时代而生。",
    "about_text": "项目结合高端白银品牌形象、清晰经济模型和长期使命：在生态系统和未来合作伙伴中发展 BTCWH 的支付用途。",
    "advantages_eyebrow": "优势",
    "advantages_title": "为什么选择 BTCWH？",
    "adv1_title": "固定供应",
    "adv1_text": "最大供应量限制为 21,000,000 BTCWH。",
    "adv2_title": "透明模型",
    "adv2_text": "流动性、储备、营销、团队和预售分配清晰。",
    "adv3_title": "社区驱动",
    "adv3_text": "项目通过社区、合作伙伴和长期实用性发展。",
    "adv4_title": "安全基础",
    "adv4_text": "btcwh.io 受 Cloudflare 保护，已准备好全球发布。",
    "tokenomics_eyebrow": "代币经济",
    "tokenomics_title": "2100 万 BTCWH，清晰分配。",
    "category": "类别",
    "share": "比例",
    "tokens": "代币",
    "liq": "流动性",
    "team": "团队",
    "reserve": "储备",
    "marketing": "营销",
    "founders_presale": "创始人预售",
    "presale_eyebrow": "创始人预售",
    "presale_title": "早期参与阶段。",
    "presale_text": "预售将持续到 1,050,000 BTCWH 全部售完。",
    "price": "价格",
    "minimum": "最低",
    "maximum": "最高",
    "allocation": "分配",
    "presale_soon": "预售即将开始",
    "presale_note": "官方合约地址和付款说明只会在 btcwh.io 和 BTCWH 官方渠道发布。",
    "roadmap_eyebrow": "路线图",
    "roadmap_title": "从品牌基础到 BTCWH Pay。",
    "phase1": "阶段 1",
    "phase1_text": "品牌、标志、域名、Cloudflare、网站。",
    "phase2": "阶段 2",
    "phase2_text": "白皮书、社区、预售基础设施。",
    "phase3": "阶段 3",
    "phase3_text": "代币发行、流动性、DEX 上线、LP 锁定。",
    "phase4": "阶段 4",
    "phase4_text": "合作伙伴、BTCWH Pay、全球生态。",
    "whitepaper_eyebrow": "白皮书",
    "whitepaper_title": "官方文件将在此发布。",
    "whitepaper_text": "BTCWH 白皮书将包含项目使命、代币经济、路线图、储备规则、预售规则和生态愿景。",
    "whitepaper_soon": "白皮书即将发布",
    "faq_title": "常见问题",
    "faq1_q": "什么是 BTCWH？",
    "faq1_a": "BTCWH 是 BTC White 的代号，一个具有长期支付生态愿景的数字资产项目。",
    "faq2_q": "官方网站是什么？",
    "faq2_a": "官方网站是 btcwh.io。",
    "faq3_q": "预售最低购买额是多少？",
    "faq3_a": "Founders Presale 最低购买额为 10 USDT。",
    "faq4_q": "BTCWH 将使用哪个区块链？",
    "faq4_a": "BTCWH 计划在 Solana 网络上发行。",
    "footer": "© 2026 BTC White. BTCWH 时代已经到来。",
    "wallet_soon_title": "钱包连接即将推出",
    "wallet_soon_text": "官方 BTCWH 预售钱包连接将在代币合约和预售智能合约发布后启用。"
  },
  "hi": {
    "nav_about": "परिचय",
    "nav_tokenomics": "टोकनोमिक्स",
    "nav_presale": "Presale",
    "nav_roadmap": "रोडमैप",
    "nav_faq": "FAQ",
    "connect_wallet": "Wallet जोड़ें",
    "hero_eyebrow": "BTCWH • SOLANA • वैश्विक भुगतान दृष्टि",
    "hero_title_1": "BTCWH का समय आ गया है।",
    "hero_title_2": "",
    "hero_lead": "BTC White नई पीढ़ी का डिजिटल एसेट है, जिसकी निश्चित सप्लाई 21,000,000 कॉइन है, पारदर्शी टोकनोमिक्स है और वास्तविक भुगतान पर ध्यान है। हम एक ऐसा इकोसिस्टम बना रहे हैं जहां क्रिप्टोकरेंसी दैनिक उपयोग का व्यावहारिक साधन बने।",
    "buy_btcwh": "BTCWH खरीदें",
    "download_whitepaper": "Whitepaper डाउनलोड करें",
    "total_supply": "कुल सप्लाई",
    "presale_price": "Presale कीमत",
    "minimum_purchase": "न्यूनतम खरीद",
    "about_eyebrow": "BTCWH के बारे में",
    "about_title": "BTC White नई डिजिटल पीढ़ी के लिए बनाया गया है।",
    "about_text": "यह प्रोजेक्ट प्रीमियम सफेद/सिल्वर ब्रांड, स्पष्ट आर्थिक मॉडल और BTCWH को भुगतान साधन के रूप में विकसित करने की दीर्घकालिक मिशन को जोड़ता है।",
    "advantages_eyebrow": "फायदे",
    "advantages_title": "BTCWH क्यों?",
    "adv1_title": "फिक्स्ड सप्लाई",
    "adv1_text": "अधिकतम सप्लाई 21,000,000 BTCWH तक सीमित है।",
    "adv2_title": "पारदर्शी मॉडल",
    "adv2_text": "लिक्विडिटी, रिजर्व, मार्केटिंग, टीम और Presale का स्पष्ट आवंटन।",
    "adv3_title": "समुदाय आधारित",
    "adv3_text": "प्रोजेक्ट समुदाय, साझेदारों और दीर्घकालिक उपयोगिता से बढ़ने के लिए बनाया गया है।",
    "adv4_title": "सुरक्षित आधार",
    "adv4_text": "btcwh.io Cloudflare द्वारा सुरक्षित है और वैश्विक प्रकाशन के लिए तैयार है।",
    "tokenomics_eyebrow": "टोकनोमिक्स",
    "tokenomics_title": "21 मिलियन BTCWH। स्पष्ट आवंटन।",
    "category": "श्रेणी",
    "share": "हिस्सा",
    "tokens": "टोकन",
    "liq": "लिक्विडिटी",
    "team": "टीम",
    "reserve": "रिजर्व",
    "marketing": "मार्केटिंग",
    "founders_presale": "Founders Presale",
    "presale_eyebrow": "Founders Presale",
    "presale_title": "शुरुआती पहुंच चरण।",
    "presale_text": "Presale 1,050,000 BTCWH की पूरी बिक्री तक जारी रहेगा।",
    "price": "कीमत",
    "minimum": "न्यूनतम",
    "maximum": "अधिकतम",
    "allocation": "आवंटन",
    "presale_soon": "Presale जल्द",
    "presale_note": "आधिकारिक कॉन्ट्रैक्ट पता और भुगतान निर्देश केवल btcwh.io और आधिकारिक BTCWH चैनलों पर प्रकाशित होंगे।",
    "roadmap_eyebrow": "रोडमैप",
    "roadmap_title": "ब्रांड से BTCWH Pay तक।",
    "phase1": "चरण 1",
    "phase1_text": "ब्रांड, लोगो, डोमेन, Cloudflare, वेबसाइट।",
    "phase2": "चरण 2",
    "phase2_text": "Whitepaper, समुदाय, Presale इंफ्रास्ट्रक्चर।",
    "phase3": "चरण 3",
    "phase3_text": "टोकन लॉन्च, लिक्विडिटी, DEX लिस्टिंग, LP लॉक।",
    "phase4": "चरण 4",
    "phase4_text": "साझेदारी, BTCWH Pay, वैश्विक इकोसिस्टम।",
    "whitepaper_eyebrow": "Whitepaper",
    "whitepaper_title": "आधिकारिक दस्तावेज यहां प्रकाशित होंगे।",
    "whitepaper_text": "BTCWH Whitepaper में प्रोजेक्ट मिशन, टोकनोमिक्स, रोडमैप, रिजर्व नियम, Presale नियम और इकोसिस्टम विजन शामिल होंगे।",
    "whitepaper_soon": "Whitepaper जल्द",
    "faq_title": "सामान्य प्रश्न",
    "faq1_q": "BTCWH क्या है?",
    "faq1_a": "BTCWH, BTC White का टिकर है — एक डिजिटल एसेट प्रोजेक्ट जिसकी दीर्घकालिक भुगतान इकोसिस्टम दृष्टि है।",
    "faq2_q": "आधिकारिक वेबसाइट क्या है?",
    "faq2_a": "आधिकारिक वेबसाइट btcwh.io है।",
    "faq3_q": "Presale न्यूनतम खरीद क्या है?",
    "faq3_a": "Founders Presale की न्यूनतम खरीद 10 USDT है।",
    "faq4_q": "BTCWH किस blockchain पर होगा?",
    "faq4_a": "BTCWH को Solana नेटवर्क पर जारी करने की योजना है।",
    "footer": "© 2026 BTC White. BTCWH का समय आ गया है।",
    "wallet_soon_title": "Wallet कनेक्शन जल्द आएगा",
    "wallet_soon_text": "आधिकारिक BTCWH Presale wallet कनेक्शन टोकन कॉन्ट्रैक्ट और Presale smart contract प्रकाशित होने के बाद सक्षम होगा।"
  },
  "es": {
    "nav_about": "Acerca de",
    "nav_tokenomics": "Tokenomics",
    "nav_presale": "Presale",
    "nav_roadmap": "Roadmap",
    "nav_faq": "FAQ",
    "connect_wallet": "Conectar wallet",
    "hero_eyebrow": "BTCWH • SOLANA • VISIÓN GLOBAL DE PAGOS",
    "hero_title_1": "Ha llegado el momento de BTCWH.",
    "hero_title_2": "",
    "hero_lead": "BTC White es un activo digital de nueva generación con un suministro fijo de 21,000,000 monedas, tokenomics transparente y un enfoque en pagos reales. Estamos construyendo un ecosistema donde la criptomoneda se convierte en una herramienta práctica para el uso diario.",
    "buy_btcwh": "Comprar BTCWH",
    "download_whitepaper": "Descargar Whitepaper",
    "total_supply": "Suministro total",
    "presale_price": "Precio Presale",
    "minimum_purchase": "Compra mínima",
    "about_eyebrow": "Sobre BTCWH",
    "about_title": "BTC White está construido para una nueva generación digital.",
    "about_text": "El proyecto combina una identidad premium blanca/plateada con un modelo económico claro y una misión a largo plazo: desarrollar BTCWH como instrumento digital de pago dentro de su ecosistema y con futuros socios.",
    "advantages_eyebrow": "Ventajas",
    "advantages_title": "¿Por qué BTCWH?",
    "adv1_title": "Suministro fijo",
    "adv1_text": "La emisión máxima está limitada a 21,000,000 BTCWH.",
    "adv2_title": "Modelo transparente",
    "adv2_text": "Asignación clara para liquidez, reserva, marketing, equipo y presale.",
    "adv3_title": "Impulsado por la comunidad",
    "adv3_text": "El proyecto está diseñado para crecer mediante comunidad, socios y utilidad a largo plazo.",
    "adv4_title": "Base segura",
    "adv4_text": "btcwh.io está protegido por Cloudflare y listo para publicación global.",
    "tokenomics_eyebrow": "Tokenomics",
    "tokenomics_title": "21 millones de BTCWH. Asignación clara.",
    "category": "Categoría",
    "share": "Porcentaje",
    "tokens": "Tokens",
    "liq": "Liquidez",
    "team": "Equipo",
    "reserve": "Reserva",
    "marketing": "Marketing",
    "founders_presale": "Founders Presale",
    "presale_eyebrow": "Founders Presale",
    "presale_title": "Fase de acceso temprano.",
    "presale_text": "La presale continúa hasta vender completamente los 1,050,000 BTCWH asignados.",
    "price": "Precio",
    "minimum": "Mínimo",
    "maximum": "Máximo",
    "allocation": "Asignación",
    "presale_soon": "Presale próximamente",
    "presale_note": "La dirección oficial del contrato y las instrucciones de pago se publicarán solo en btcwh.io y canales oficiales de BTCWH.",
    "roadmap_eyebrow": "Roadmap",
    "roadmap_title": "Desde la base de marca hasta BTCWH Pay.",
    "phase1": "Fase 1",
    "phase1_text": "Marca, logo, dominio, Cloudflare, sitio web.",
    "phase2": "Fase 2",
    "phase2_text": "Whitepaper, comunidad, infraestructura Presale.",
    "phase3": "Fase 3",
    "phase3_text": "Lanzamiento del token, liquidez, listado DEX, bloqueo LP.",
    "phase4": "Fase 4",
    "phase4_text": "Socios, BTCWH Pay, ecosistema global.",
    "whitepaper_eyebrow": "Whitepaper",
    "whitepaper_title": "La documentación oficial se publicará aquí.",
    "whitepaper_text": "El Whitepaper de BTCWH incluirá misión, tokenomics, roadmap, reglas de reserva, reglas de presale y visión del ecosistema.",
    "whitepaper_soon": "Whitepaper próximamente",
    "faq_title": "Preguntas frecuentes",
    "faq1_q": "¿Qué es BTCWH?",
    "faq1_a": "BTCWH es el ticker de BTC White, un proyecto de activo digital con visión de ecosistema de pagos a largo plazo.",
    "faq2_q": "¿Cuál es el sitio oficial?",
    "faq2_a": "El sitio oficial es btcwh.io.",
    "faq3_q": "¿Cuál es la compra mínima de Presale?",
    "faq3_a": "La compra mínima en Founders Presale es 10 USDT.",
    "faq4_q": "¿Qué blockchain usará BTCWH?",
    "faq4_a": "BTCWH está previsto para la red Solana.",
    "footer": "© 2026 BTC White. Ha llegado el momento de BTCWH.",
    "wallet_soon_title": "La conexión de wallet llegará pronto",
    "wallet_soon_text": "La conexión oficial de wallet para BTCWH Presale se activará solo después de publicar el contrato del token y el smart contract de presale."
  },
  "ko": {
    "nav_about": "소개",
    "nav_tokenomics": "토크노믹스",
    "nav_presale": "프리세일",
    "nav_roadmap": "로드맵",
    "nav_faq": "FAQ",
    "connect_wallet": "지갑 연결",
    "hero_eyebrow": "BTCWH • SOLANA • 글로벌 결제 비전",
    "hero_title_1": "BTCWH의 시간이 왔습니다.",
    "hero_title_2": "",
    "hero_lead": "BTC White는 21,000,000개로 고정된 공급량, 투명한 토크노믹스, 실제 결제에 대한 초점을 가진 차세대 디지털 자산입니다. 우리는 암호화폐가 일상에서 실용적인 도구가 되는 생태계를 구축하고 있습니다.",
    "buy_btcwh": "BTCWH 구매",
    "download_whitepaper": "백서 다운로드",
    "total_supply": "총 공급량",
    "presale_price": "프리세일 가격",
    "minimum_purchase": "최소 구매",
    "about_eyebrow": "BTCWH 소개",
    "about_title": "BTC White는 새로운 디지털 세대를 위해 만들어졌습니다.",
    "about_text": "이 프로젝트는 프리미엄 화이트/실버 브랜드, 명확한 경제 모델, 생태계와 미래 파트너 안에서 BTCWH를 결제 수단으로 발전시키는 장기 미션을 결합합니다.",
    "advantages_eyebrow": "장점",
    "advantages_title": "왜 BTCWH인가?",
    "adv1_title": "고정 공급량",
    "adv1_text": "최대 발행량은 21,000,000 BTCWH로 제한됩니다.",
    "adv2_title": "투명한 모델",
    "adv2_text": "유동성, 준비금, 마케팅, 팀, 프리세일에 대한 명확한 배분.",
    "adv3_title": "커뮤니티 중심",
    "adv3_text": "프로젝트는 커뮤니티, 파트너, 장기 유틸리티를 통해 성장하도록 설계되었습니다.",
    "adv4_title": "안전한 기반",
    "adv4_text": "btcwh.io는 Cloudflare로 보호되며 글로벌 공개 준비가 되어 있습니다.",
    "tokenomics_eyebrow": "토크노믹스",
    "tokenomics_title": "2,100만 BTCWH. 명확한 배분.",
    "category": "카테고리",
    "share": "비율",
    "tokens": "토큰",
    "liq": "유동성",
    "team": "팀",
    "reserve": "준비금",
    "marketing": "마케팅",
    "founders_presale": "파운더스 프리세일",
    "presale_eyebrow": "파운더스 프리세일",
    "presale_title": "초기 접근 단계.",
    "presale_text": "프리세일은 할당된 1,050,000 BTCWH가 모두 판매될 때까지 계속됩니다.",
    "price": "가격",
    "minimum": "최소",
    "maximum": "최대",
    "allocation": "할당",
    "presale_soon": "프리세일 예정",
    "presale_note": "공식 계약 주소와 결제 안내는 btcwh.io 및 BTCWH 공식 채널에서만 공개됩니다.",
    "roadmap_eyebrow": "로드맵",
    "roadmap_title": "브랜드 기반에서 BTCWH Pay까지.",
    "phase1": "1단계",
    "phase1_text": "브랜드, 로고, 도메인, Cloudflare, 웹사이트.",
    "phase2": "2단계",
    "phase2_text": "백서, 커뮤니티, 프리세일 인프라.",
    "phase3": "3단계",
    "phase3_text": "토큰 출시, 유동성, DEX 상장, LP 락업.",
    "phase4": "4단계",
    "phase4_text": "파트너십, BTCWH Pay, 글로벌 생태계.",
    "whitepaper_eyebrow": "백서",
    "whitepaper_title": "공식 문서는 여기에 게시됩니다.",
    "whitepaper_text": "BTCWH 백서에는 프로젝트 미션, 토크노믹스, 로드맵, 준비금 규칙, 프리세일 규칙 및 생태계 비전이 포함됩니다.",
    "whitepaper_soon": "백서 곧 공개",
    "faq_title": "자주 묻는 질문",
    "faq1_q": "BTCWH란 무엇인가요?",
    "faq1_a": "BTCWH는 장기 결제 생태계 비전을 가진 디지털 자산 프로젝트 BTC White의 티커입니다.",
    "faq2_q": "공식 웹사이트는 무엇인가요?",
    "faq2_a": "공식 웹사이트는 btcwh.io입니다.",
    "faq3_q": "프리세일 최소 구매 금액은?",
    "faq3_a": "Founders Presale 최소 구매 금액은 10 USDT입니다.",
    "faq4_q": "BTCWH는 어떤 블록체인을 사용하나요?",
    "faq4_a": "BTCWH는 Solana 네트워크에서 발행될 예정입니다.",
    "footer": "© 2026 BTC White. BTCWH의 시간이 왔습니다.",
    "wallet_soon_title": "지갑 연결 준비 중",
    "wallet_soon_text": "공식 BTCWH 프리세일 지갑 연결은 토큰 계약과 프리세일 스마트 계약이 공개된 후 활성화됩니다."
  }
};

function setLang(lang) {
  const base = translations.en;
  const t = Object.assign({}, base, translations[lang] || {});
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.dataset.i18n;
    if (t[key]) el.textContent = t[key];
  });
  localStorage.setItem("btcwh_lang", lang);
  document.documentElement.lang = lang;
}

const languageSelect = document.getElementById("languageSelect");
const savedLang = localStorage.getItem("btcwh_lang") || "en";
if (languageSelect) {
  languageSelect.value = savedLang;
  setLang(savedLang);
  languageSelect.addEventListener("change", e => setLang(e.target.value));
}

const themeToggle = document.getElementById("themeToggle");
function applyTheme(mode) {
  document.body.classList.toggle("dark", mode === "dark");
  if (themeToggle) themeToggle.textContent = mode === "dark" ? "☀️" : "🌙";
  localStorage.setItem("btcwh_theme", mode);
}
applyTheme(localStorage.getItem("btcwh_theme") || "light");
if (themeToggle) {
  themeToggle.addEventListener("click", () => {
    const next = document.body.classList.contains("dark") ? "light" : "dark";
    applyTheme(next);
  });
}

const modal = document.getElementById("walletModal");
const walletBtn = document.getElementById("walletBtn");
const closeModal = document.getElementById("closeModal");
if (walletBtn && modal) walletBtn.addEventListener("click", () => modal.classList.add("show"));
if (closeModal && modal) closeModal.addEventListener("click", () => modal.classList.remove("show"));
if (modal) modal.addEventListener("click", e => { if (e.target === modal) modal.classList.remove("show"); });

const items = document.querySelectorAll(".reveal");
const obs = new IntersectionObserver(entries => entries.forEach(e => {
  if (e.isIntersecting) e.target.classList.add("visible");
}), { threshold: 0.1 });
items.forEach(i => obs.observe(i));
